/*
 * ECG Restful API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: vincent71497867@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RPNDevicePair : IEquatable<RPNDevicePair>
    { 
        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [Required]
        [DataMember(Name="date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Gets or Sets PairStatus
        /// </summary>
        [Required]
        [DataMember(Name="pair_status")]
        public string PairStatus { get; set; }

        /// <summary>
        /// Gets or Sets DeviceInfo
        /// </summary>
        [Required]
        [DataMember(Name="device_info")]
        public RPNDevicePairDeviceInfo DeviceInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RPNDevicePair {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  PairStatus: ").Append(PairStatus).Append("\n");
            sb.Append("  DeviceInfo: ").Append(DeviceInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RPNDevicePair)obj);
        }

        /// <summary>
        /// Returns true if RPNDevicePair instances are equal
        /// </summary>
        /// <param name="other">Instance of RPNDevicePair to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RPNDevicePair other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Date == other.Date ||
                    Date != null &&
                    Date.Equals(other.Date)
                ) && 
                (
                    PairStatus == other.PairStatus ||
                    PairStatus != null &&
                    PairStatus.Equals(other.PairStatus)
                ) && 
                (
                    DeviceInfo == other.DeviceInfo ||
                    DeviceInfo != null &&
                    DeviceInfo.Equals(other.DeviceInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Date != null)
                    hashCode = hashCode * 59 + Date.GetHashCode();
                    if (PairStatus != null)
                    hashCode = hashCode * 59 + PairStatus.GetHashCode();
                    if (DeviceInfo != null)
                    hashCode = hashCode * 59 + DeviceInfo.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RPNDevicePair left, RPNDevicePair right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RPNDevicePair left, RPNDevicePair right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
